name: build-and-test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        nimversion:
          - binary:stable
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v5
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Linux deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -q
        sudo apt-get install -y libsodium-dev
    - name: Install macOS deps
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install libsodium
        printf "DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Test
      run: |
        nim c -d:nimDebugDlOpen -r test_sodium.nim
